"""Generated-only formal-shape numerical evidence for PACRE-VC v23.

Every random input in this module is generated by an independent CPU
``torch.Generator`` and only then copied to the selected device.  Receipts
contain raw-bit fingerprints and scalar summaries, never tensor contents.

The v22 subtractive algebra is replayed only as a zero-decision-weight
attribution ledger.  Gate decisions use exact replay of the operations that
the forward actually executes, analytic FP32 phase bounds, and integrity
checks for the local CPU-FP64 oracle.
"""

from __future__ import annotations

from dataclasses import dataclass, fields as dataclass_fields
import math
from typing import Final, Mapping

import torch
from torch import Tensor
from torch.nn import functional as F

from cure_lite.cache.schema import stable_fingerprint
from cure_lite.paired_types import tensor_content_fingerprint
from cure_lite_v22.pacre import (
    CURELitePhaseAlignedCenteredResidualCompatibilityEnergyLevelSet,
    CoverageStatePACREConfig,
    CoverageStatePACREFields,
)

from .algebra_verifier import (
    EPS32,
    TINY32,
    phase_roundoff_observations,
    verify_pacre_v22_forward_fields,
)
from .environment import (
    fingerprinted_runtime_environment,
    verify_runtime_environment,
)
from .numerical_diagnostics import (
    PACRE_VC_LEGACY_ATOL,
    PACRE_VC_LEGACY_RTOL,
    legacy_subtraction_diagnostics,
    run_pacre_fp64_oracle,
)
from .pacre_vc import (
    CURELitePACREVerifierCorrectedLevelSet,
    CoverageStatePACREVerifierCorrectedConfig,
)
from .protocol import source_closure_payload, verify_source_closure


PACRE_VC_SCALAR_COUNTEREXAMPLE_SCHEMA: Final = (
    "cure-lite-v23-pacre-vc-scalar-counterexamples-v1"
)
PACRE_VC_FORMAL_STRESS_RUN_SCHEMA: Final = (
    "cure-lite-v23-pacre-vc-formal-numeric-stress-run-v1"
)
PACRE_VC_FORMAL_STRESS_SCHEMA: Final = (
    "cure-lite-v23-pacre-vc-formal-numeric-stress-receipt-v1"
)
PACRE_VC_FORMAL_STRESS_SEEDS: Final = (42, 43, 44)
PACRE_VC_FORMAL_BATCH_SIZE: Final = 1
PACRE_VC_FORMAL_FEATURE_CHANNELS: Final = 64
PACRE_VC_FORMAL_FEATURE_STRIDE: Final = 4
PACRE_VC_FORMAL_WIDTH: Final = 32
PACRE_VC_FORMAL_FEATURE_HEIGHT: Final = 64
PACRE_VC_FORMAL_FEATURE_WIDTH: Final = 64
PACRE_VC_FORMAL_OCCUPANCY_HEIGHT: Final = 256
PACRE_VC_FORMAL_OCCUPANCY_WIDTH: Final = 256
PACRE_VC_FORMAL_OCCUPANCY_THRESHOLD: Final = 0.68
PACRE_VC_MODEL_INITIALIZATION_SEED_OFFSET: Final = 230_000
PACRE_VC_SCALAR_COUNTEREXAMPLES: Final = (
    ("common_100_residual_0p1", 100.0, 0.1),
    ("common_10_residual_0p01", 10.0, 0.01),
)


@dataclass(frozen=True)
class GeneratedPACREVCFormalInput:
    """One canonical, generated-only CPU formal-shape input."""

    seed: int
    feature: Tensor
    occupancy: Tensor
    manifest: dict[str, object]


def _resolve_device(device: torch.device | str) -> torch.device:
    resolved = torch.device(device)
    if resolved == torch.device("cpu"):
        return resolved
    if resolved.type != "cuda":
        raise ValueError("formal stress supports only CPU or cuda:0")
    if not torch.cuda.is_available():
        raise RuntimeError("formal CUDA stress was requested but unavailable")
    if resolved.index is None:
        resolved = torch.device("cuda:0")
    if resolved != torch.device("cuda:0"):
        raise ValueError("the frozen selected device is cuda:0")
    if torch.cuda.device_count() < 1:
        raise RuntimeError("cuda:0 is unavailable")
    return resolved


def _self_fingerprint(
    payload: Mapping[str, object],
    *,
    field: str,
) -> str:
    if not isinstance(payload, Mapping):
        raise TypeError("fingerprinted evidence must be a mapping")
    body = dict(payload)
    observed = body.pop(field, None)
    expected = stable_fingerprint(body)
    if (
        not isinstance(observed, str)
        or len(observed) != 64
        or observed != expected
    ):
        raise ValueError(f"invalid {field}")
    return observed


def _tensor_summary(value: Tensor) -> dict[str, object]:
    if not isinstance(value, Tensor):
        raise TypeError("tensor summary requires a tensor")
    if value.numel() < 1:
        raise ValueError("formal tensor cannot be empty")
    return {
        "shape": [int(extent) for extent in value.shape],
        "dtype": str(value.dtype),
        "raw_fingerprint": tensor_content_fingerprint(value),
    }


def _state_summary(model: torch.nn.Module) -> dict[str, object]:
    tensors = {
        name: _tensor_summary(value)
        for name, value in sorted(model.state_dict().items())
    }
    body: dict[str, object] = {"tensors": tensors}
    return {**body, "raw_fingerprint": stable_fingerprint(body)}


def _fields_summary(
    value: CoverageStatePACREFields,
) -> dict[str, object]:
    if type(value) is not CoverageStatePACREFields:
        raise TypeError("formal stress requires the exact v22 fields type")
    tensors: dict[str, object] = {}
    output_size: list[int] | None = None
    for definition in dataclass_fields(CoverageStatePACREFields):
        item = getattr(value, definition.name)
        if isinstance(item, Tensor):
            tensors[definition.name] = _tensor_summary(item)
        elif definition.name == "output_size":
            output_size = [int(extent) for extent in item]
        else:
            raise TypeError("unsupported PACRE fields member")
    body: dict[str, object] = {
        "fields_fqcn": (
            f"{type(value).__module__}.{type(value).__qualname__}"
        ),
        "tensors": tensors,
        "output_size": output_size,
    }
    return {**body, "raw_fingerprint": stable_fingerprint(body)}


def generate_pacre_vc_formal_input(
    seed: int,
) -> GeneratedPACREVCFormalInput:
    """Generate one frozen input using only an independent CPU generator."""

    if (
        isinstance(seed, bool)
        or not isinstance(seed, int)
        or seed not in PACRE_VC_FORMAL_STRESS_SEEDS
    ):
        raise ValueError("seed must be one of the frozen formal seeds")
    global_state = torch.random.get_rng_state().clone()
    generator = torch.Generator(device="cpu").manual_seed(seed)
    feature = torch.randn(
        (
            PACRE_VC_FORMAL_BATCH_SIZE,
            PACRE_VC_FORMAL_FEATURE_CHANNELS,
            PACRE_VC_FORMAL_FEATURE_HEIGHT,
            PACRE_VC_FORMAL_FEATURE_WIDTH,
        ),
        generator=generator,
        dtype=torch.float32,
        device="cpu",
    ).contiguous()
    occupancy = (
        torch.rand(
            (
                PACRE_VC_FORMAL_BATCH_SIZE,
                1,
                PACRE_VC_FORMAL_OCCUPANCY_HEIGHT,
                PACRE_VC_FORMAL_OCCUPANCY_WIDTH,
            ),
            generator=generator,
            dtype=torch.float32,
            device="cpu",
        )
        > PACRE_VC_FORMAL_OCCUPANCY_THRESHOLD
    ).contiguous()
    global_rng_preserved = torch.equal(
        global_state,
        torch.random.get_rng_state(),
    )
    if not global_rng_preserved:
        raise AssertionError("independent input generator changed global RNG")
    input_rows = {
        "feature": _tensor_summary(feature),
        "occupancy": _tensor_summary(occupancy),
    }
    body: dict[str, object] = {
        "generator_device": "cpu",
        "generator_kind": "independent_torch_generator",
        "seed": seed,
        "generation_order": ["feature_randn", "occupancy_rand_threshold"],
        "occupancy_threshold_hex": (
            PACRE_VC_FORMAL_OCCUPANCY_THRESHOLD.hex()
        ),
        "global_cpu_rng_preserved": global_rng_preserved,
        "tensors": input_rows,
        "occupancy_true_count": int(occupancy.sum().item()),
    }
    manifest = {
        **body,
        "manifest_fingerprint": stable_fingerprint(body),
    }
    return GeneratedPACREVCFormalInput(
        seed=seed,
        feature=feature,
        occupancy=occupancy,
        manifest=manifest,
    )


def _build_model_pair(
    *,
    seed: int,
    device: torch.device,
) -> tuple[
    CURELitePhaseAlignedCenteredResidualCompatibilityEnergyLevelSet,
    CURELitePACREVerifierCorrectedLevelSet,
]:
    initialization_seed = (
        seed + PACRE_VC_MODEL_INITIALIZATION_SEED_OFFSET
    )
    with torch.random.fork_rng(devices=[]):
        torch.random.default_generator.manual_seed(initialization_seed)
        v22 = (
            CURELitePhaseAlignedCenteredResidualCompatibilityEnergyLevelSet(
                CoverageStatePACREConfig(
                    feature_channels=PACRE_VC_FORMAL_FEATURE_CHANNELS,
                    feature_stride=PACRE_VC_FORMAL_FEATURE_STRIDE,
                    width=PACRE_VC_FORMAL_WIDTH,
                )
            )
        )
        torch.random.default_generator.manual_seed(initialization_seed)
        v23 = CURELitePACREVerifierCorrectedLevelSet(
            CoverageStatePACREVerifierCorrectedConfig(
                feature_channels=PACRE_VC_FORMAL_FEATURE_CHANNELS,
                feature_stride=PACRE_VC_FORMAL_FEATURE_STRIDE,
                width=PACRE_VC_FORMAL_WIDTH,
            )
        )
    if _state_summary(v22) != _state_summary(v23):
        raise AssertionError("v22/v23 initialization differs before device copy")
    return v22.to(device=device), v23.to(device=device)


def _failed_isclose_count(
    actual: Tensor,
    expected: Tensor,
    *,
    rtol: float,
    atol: float,
) -> int:
    return int(
        (
            ~torch.isclose(actual, expected, rtol=rtol, atol=atol)
        )
        .sum()
        .detach()
        .cpu()
        .item()
    )


@torch.no_grad()
def _legacy_six_check_ledger(
    fields: CoverageStatePACREFields,
) -> dict[str, object]:
    residual = fields.phase_feature_residual
    phases = int(residual.shape[1])
    tolerance = (
        4.0
        * float(phases)
        * EPS32
        * (
            1.0
            + float(
                fields.phase_feature_affine.detach().abs().amax().cpu()
            )
        )
    )
    legacy = legacy_subtraction_diagnostics(fields)
    reconstruction_failed = _failed_isclose_count(
        fields.phase_feature_mean + residual,
        fields.phase_feature_affine,
        rtol=0.0,
        atol=tolerance,
    )
    centering_failed = int(
        (residual.sum(dim=1).abs() > tolerance)
        .sum()
        .detach()
        .cpu()
        .item()
    )
    actual_hidden_failed = _failed_isclose_count(
        fields.actual_compatibility_hidden,
        F.silu(fields.actual_specific_joint_affine)
        - F.silu(fields.actual_common_joint_affine),
        rtol=PACRE_VC_LEGACY_RTOL,
        atol=PACRE_VC_LEGACY_ATOL,
    )
    flipped_hidden_failed = _failed_isclose_count(
        fields.flipped_compatibility_hidden,
        F.silu(fields.flipped_specific_joint_affine)
        - F.silu(fields.flipped_common_joint_affine),
        rtol=PACRE_VC_LEGACY_RTOL,
        atol=PACRE_VC_LEGACY_ATOL,
    )
    failures = (
        (
            "phase_reconstruction",
            reconstruction_failed,
            "rtol_0_atol_state_scale",
        ),
        (
            "phase_centering",
            centering_failed,
            "absolute_state_scale_bound",
        ),
        (
            "actual_subtractive_residual",
            legacy.actual.failed_under_v22_allclose_count,
            "rtol_2e-6_atol_2e-7",
        ),
        (
            "flipped_subtractive_residual",
            legacy.flipped.failed_under_v22_allclose_count,
            "rtol_2e-6_atol_2e-7",
        ),
        (
            "actual_hidden_replay",
            actual_hidden_failed,
            "rtol_2e-6_atol_2e-7",
        ),
        (
            "flipped_hidden_replay",
            flipped_hidden_failed,
            "rtol_2e-6_atol_2e-7",
        ),
    )
    rows = [
        {
            "name": name,
            "gate_eligible": False,
            "decision_weight": 0,
            "failed_element_count": count,
            "passed_under_v22_check": count == 0,
            "tolerance_policy": policy,
        }
        for name, count, policy in failures
    ]
    return {
        "formula_count": len(rows),
        "expected_formula_count": 6,
        "formula_order": [row["name"] for row in rows],
        "state_binding": "same_forward_fields_object",
        "legacy_phase_tolerance_hex": tolerance.hex(),
        "rows": rows,
        "complete": len(rows) == 6,
        "all_diagnostic_only": all(
            row["gate_eligible"] is False
            and row["decision_weight"] == 0
            for row in rows
        ),
        "legacy_outcomes_gate_eligible": False,
    }


def _swallow_ledger_integrity(
    oracle: object,
) -> dict[str, object]:
    numerical = oracle.numerical
    observations = (
        numerical.actual_joint_swallow,
        numerical.flipped_joint_swallow,
        numerical.actual_hidden_swallow,
        numerical.flipped_hidden_swallow,
        numerical.zero_readout.actual_energy_swallow,
        numerical.zero_readout.flipped_energy_swallow,
        numerical.zero_readout.interaction_swallow,
        numerical.fixed_readout.actual_energy_swallow,
        numerical.fixed_readout.flipped_energy_swallow,
        numerical.fixed_readout.interaction_swallow,
    )
    names = [item.name for item in observations]
    count_ranges_valid = all(
        0 <= item.swallowed_element_count <= item.eligible_element_count
        and math.isfinite(item.maximum_swallowed_reference_magnitude)
        and item.maximum_swallowed_reference_magnitude >= 0.0
        for item in observations
    )
    all_diagnostic_only = all(
        item.gate_eligible is False for item in observations
    )
    passed = (
        len(observations) == 10
        and len(names) == len(set(names))
        and count_ranges_valid
        and all_diagnostic_only
    )
    return {
        "passed": passed,
        "expected_observation_count": 10,
        "observed_observation_count": len(observations),
        "unique_names": len(names) == len(set(names)),
        "count_ranges_valid": count_ranges_valid,
        "all_magnitudes_finite": count_ranges_valid,
        "all_diagnostic_only": all_diagnostic_only,
        "decision_uses_swallow_counts": False,
        "observations": [
            item.canonical_payload() for item in observations
        ],
    }


@torch.no_grad()
def _fixed_readout_observation(
    fields: CoverageStatePACREFields,
) -> dict[str, object]:
    readout = torch.linspace(
        0.5,
        1.5,
        PACRE_VC_FORMAL_WIDTH,
        dtype=torch.float32,
        device="cpu",
    ).to(device=fields.field.device)
    weight = readout[None, None, :, None, None]
    actual = (
        fields.actual_compatibility_hidden * weight
    ).sum(dim=2)
    flipped = (
        fields.flipped_compatibility_hidden * weight
    ).sum(dim=2)
    interaction = 0.5 * (actual - flipped)
    nonzero_count = int(
        torch.count_nonzero(interaction).detach().cpu().item()
    )
    maximum = float(interaction.abs().amax().detach().cpu().item())
    return {
        "policy": "cpu_fp32_linspace_0.5_to_1.5_then_device_copy",
        "readout_raw_fingerprint": tensor_content_fingerprint(readout),
        "readout_exact_zero": bool(torch.count_nonzero(readout) == 0),
        "interaction_nonzero_count": nonzero_count,
        "maximum_interaction_magnitude_hex": maximum.hex(),
        "passed": (
            bool(torch.all(readout > 0.0))
            and nonzero_count > 0
            and math.isfinite(maximum)
        ),
    }


def _run_frozen_formal_stress(
    *,
    generated: GeneratedPACREVCFormalInput,
    device: torch.device,
    runtime_fingerprint: str,
    source_fingerprint: str,
) -> dict[str, object]:
    before_cpu_rng = torch.random.get_rng_state().clone()
    before_cuda_rng = (
        torch.cuda.get_rng_state(device).clone()
        if device.type == "cuda"
        else None
    )
    feature = generated.feature.to(device=device).contiguous()
    occupancy = generated.occupancy.to(device=device).contiguous()
    copied_input = {
        "feature": _tensor_summary(feature),
        "occupancy": _tensor_summary(occupancy),
    }
    copy_preserved = all(
        copied_input[name]["raw_fingerprint"]
        == generated.manifest["tensors"][name]["raw_fingerprint"]
        for name in ("feature", "occupancy")
    )

    v22, v23 = _build_model_pair(seed=generated.seed, device=device)
    initial_v22 = _state_summary(v22)
    initial_v23 = _state_summary(v23)
    state_dict_parity = initial_v22 == initial_v23

    # The candidate forward is verified immediately.  This frozen order keeps
    # the same-device transcendental replay adjacent to the operation under
    # audit, before the independent v22 reference allocates its field ledger.
    with torch.no_grad():
        fields_v23 = v23.forward_fields(feature, occupancy)
    fields_v23_summary = _fields_summary(fields_v23)
    algebra = verify_pacre_v22_forward_fields(v23, fields_v23)
    legacy = legacy_subtraction_diagnostics(fields_v23)
    legacy_six = _legacy_six_check_ledger(fields_v23)
    oracle = run_pacre_fp64_oracle(v23, fields_v23)
    swallow_integrity = _swallow_ledger_integrity(oracle)
    fixed_readout = _fixed_readout_observation(fields_v23)
    final_v23 = _state_summary(v23)
    v23_preserved = initial_v23 == final_v23
    v23_gradients_clear = all(
        parameter.grad is None for parameter in v23.parameters()
    )
    del fields_v23

    with torch.no_grad():
        fields_v22 = v22.forward_fields(feature, occupancy)
    fields_v22_summary = _fields_summary(fields_v22)
    final_v22 = _state_summary(v22)
    v22_preserved = initial_v22 == final_v22
    v22_gradients_clear = all(
        parameter.grad is None for parameter in v22.parameters()
    )
    del fields_v22

    fields_parity = fields_v22_summary == fields_v23_summary
    replay_check_count = len(algebra.exact_replay.checks)
    zero_bound_exact_check_count = sum(
        check.maximum_bound == 0.0
        for check in algebra.exact_replay.checks
    )
    bounded_hidden_check_count = sum(
        check.maximum_bound > 0.0
        and check.name.endswith("_hidden_forward_bounded")
        for check in algebra.exact_replay.checks
    )
    field_tensor_count = len(fields_v23_summary["tensors"])
    ledger_complete = (
        field_tensor_count
        == len(dataclass_fields(CoverageStatePACREFields)) - 1
        and replay_check_count == 15
        and zero_bound_exact_check_count == 13
        and bounded_hidden_check_count == 2
        and legacy_six["complete"] is True
        and legacy_six["all_diagnostic_only"] is True
        and swallow_integrity["passed"] is True
    )
    cpu_rng_preserved = torch.equal(
        before_cpu_rng,
        torch.random.get_rng_state(),
    )
    selected_rng_preserved = (
        before_cuda_rng is None
        or torch.equal(before_cuda_rng, torch.cuda.get_rng_state(device))
    )
    gate_passed = (
        copy_preserved
        and state_dict_parity
        and fields_parity
        and algebra.passed
        and oracle.integrity.passed
        and swallow_integrity["passed"] is True
        and fixed_readout["passed"] is True
        and ledger_complete
        and v22_preserved
        and v23_preserved
        and v22_gradients_clear
        and v23_gradients_clear
        and cpu_rng_preserved
        and selected_rng_preserved
    )
    body: dict[str, object] = {
        "schema_version": PACRE_VC_FORMAL_STRESS_RUN_SCHEMA,
        "candidate_pair": ["PACRE-v22", "PACRE-VC-v23"],
        "device": str(device),
        "seed": generated.seed,
        "forward_execution_order": [
            "v23_candidate_then_immediate_verifier_and_oracle",
            "v22_reference_then_raw_field_comparison",
        ],
        "input_manifest": generated.manifest,
        "device_copy": copied_input,
        "device_copy_raw_bits_preserved": copy_preserved,
        "model_initialization_seed": (
            generated.seed + PACRE_VC_MODEL_INITIALIZATION_SEED_OFFSET
        ),
        "initial_model_state": {
            "passed": state_dict_parity,
            "v22": initial_v22,
            "v23": initial_v23,
        },
        "all_fields_raw_parity": {
            "passed": fields_parity,
            "v22": fields_v22_summary,
            "v23": fields_v23_summary,
        },
        "algebra_verification": algebra.canonical_payload(),
        "legacy_subtraction_diagnostics": legacy.canonical_payload(),
        "legacy_six_check_replay": legacy_six,
        "fp64_oracle": oracle.canonical_payload(),
        "signal_swallow_ledger_integrity": swallow_integrity,
        "fixed_readout_nonzero_observation": fixed_readout,
        "ledger": {
            "complete": ledger_complete,
            "field_tensor_count": field_tensor_count,
            "algebra_replay_check_count": replay_check_count,
            "zero_bound_exact_check_count": zero_bound_exact_check_count,
            "bounded_hidden_check_count": bounded_hidden_check_count,
            "phase_semantic_check_count": 2,
            "legacy_formula_count": legacy_six["formula_count"],
            "swallow_observation_count": swallow_integrity[
                "observed_observation_count"
            ],
        },
        "model_state_preserved": {
            "v22": v22_preserved,
            "v23": v23_preserved,
        },
        "gradient_buffers_unchanged": {
            "v22": v22_gradients_clear,
            "v23": v23_gradients_clear,
        },
        "global_cpu_rng_preserved": cpu_rng_preserved,
        "selected_device_rng_preserved": selected_rng_preserved,
        "runtime_environment_fingerprint": runtime_fingerprint,
        "source_closure_fingerprint": source_fingerprint,
        "gate_passed": gate_passed,
        "generated_only": True,
        "dataset_accessed": False,
        "cache_accessed": False,
        "D_R_accessed": False,
        "D_V_accessed": False,
        "D_T_accessed": False,
        "optimizer_constructed": False,
        "training_performed": False,
    }
    return {**body, "run_fingerprint": stable_fingerprint(body)}


def run_pacre_vc_formal_numeric_stress_run(
    *,
    device: torch.device | str,
    seed: int,
    runtime_environment: Mapping[str, object] | None = None,
    source_closure: Mapping[str, object] | None = None,
) -> dict[str, object]:
    """Run one formal shape/seed probe with pre-input runtime locking."""

    resolved = _resolve_device(device)
    locked_runtime = (
        fingerprinted_runtime_environment(resolved)
        if runtime_environment is None
        else dict(runtime_environment)
    )
    runtime_fingerprint = verify_runtime_environment(
        locked_runtime,
        resolved,
    )
    locked_source = (
        source_closure_payload()
        if source_closure is None
        else dict(source_closure)
    )
    source_fingerprint = verify_source_closure(locked_source)
    generated = generate_pacre_vc_formal_input(seed)
    result = _run_frozen_formal_stress(
        generated=generated,
        device=resolved,
        runtime_fingerprint=runtime_fingerprint,
        source_fingerprint=source_fingerprint,
    )
    if (
        verify_runtime_environment(locked_runtime, resolved)
        != runtime_fingerprint
        or verify_source_closure(locked_source) != source_fingerprint
    ):
        raise RuntimeError("formal stress locks changed during execution")
    return result


def run_pacre_vc_formal_numeric_stress_receipt(
    *,
    device: torch.device | str,
    runtime_environment: Mapping[str, object] | None = None,
    source_closure: Mapping[str, object] | None = None,
) -> dict[str, object]:
    """Run all three seeds on one frozen device and return one receipt."""

    resolved = _resolve_device(device)
    locked_runtime = (
        fingerprinted_runtime_environment(resolved)
        if runtime_environment is None
        else dict(runtime_environment)
    )
    runtime_fingerprint = verify_runtime_environment(
        locked_runtime,
        resolved,
    )
    locked_source = (
        source_closure_payload()
        if source_closure is None
        else dict(source_closure)
    )
    source_fingerprint = verify_source_closure(locked_source)
    # Both locks above are created/verified before any generated input.
    generated_inputs = [
        generate_pacre_vc_formal_input(seed)
        for seed in PACRE_VC_FORMAL_STRESS_SEEDS
    ]
    runs = [
        _run_frozen_formal_stress(
            generated=generated,
            device=resolved,
            runtime_fingerprint=runtime_fingerprint,
            source_fingerprint=source_fingerprint,
        )
        for generated in generated_inputs
    ]
    runtime_verified_post = (
        verify_runtime_environment(locked_runtime, resolved)
        == runtime_fingerprint
    )
    source_verified_post = (
        verify_source_closure(locked_source) == source_fingerprint
    )
    manifests = [generated.manifest for generated in generated_inputs]
    manifest_body: dict[str, object] = {
        "generator_device": "cpu",
        "seeds": list(PACRE_VC_FORMAL_STRESS_SEEDS),
        "manifests": manifests,
    }
    aggregate_manifest = {
        **manifest_body,
        "manifest_fingerprint": stable_fingerprint(manifest_body),
    }
    body: dict[str, object] = {
        "schema_version": PACRE_VC_FORMAL_STRESS_SCHEMA,
        "candidate_pair": ["PACRE-v22", "PACRE-VC-v23"],
        "device": str(resolved),
        "formal_shape": {
            "batch_size": PACRE_VC_FORMAL_BATCH_SIZE,
            "feature_channels": PACRE_VC_FORMAL_FEATURE_CHANNELS,
            "feature_stride": PACRE_VC_FORMAL_FEATURE_STRIDE,
            "hidden_width": PACRE_VC_FORMAL_WIDTH,
            "feature_grid": [
                PACRE_VC_FORMAL_FEATURE_HEIGHT,
                PACRE_VC_FORMAL_FEATURE_WIDTH,
            ],
            "occupancy_grid": [
                PACRE_VC_FORMAL_OCCUPANCY_HEIGHT,
                PACRE_VC_FORMAL_OCCUPANCY_WIDTH,
            ],
            "dtype": "torch.float32",
        },
        "required_seeds": list(PACRE_VC_FORMAL_STRESS_SEEDS),
        "canonical_cpu_input_manifest": aggregate_manifest,
        "runtime_environment": locked_runtime,
        "runtime_environment_verified_pre_input_generation": True,
        "runtime_environment_verified_post_execution": (
            runtime_verified_post
        ),
        "source_closure": locked_source,
        "source_closure_verified_pre_input_generation": True,
        "source_closure_verified_post_execution": source_verified_post,
        "runs": runs,
        "expected_run_count": len(PACRE_VC_FORMAL_STRESS_SEEDS),
        "observed_run_count": len(runs),
        "gate_passed": (
            len(runs) == len(PACRE_VC_FORMAL_STRESS_SEEDS)
            and all(run["gate_passed"] is True for run in runs)
            and runtime_verified_post
            and source_verified_post
        ),
        "generated_only": True,
        "dataset_accessed": False,
        "cache_accessed": False,
        "D_R_accessed": False,
        "D_V_accessed": False,
        "D_T_accessed": False,
        "optimizer_constructed": False,
        "training_performed": False,
    }
    return {**body, "receipt_fingerprint": stable_fingerprint(body)}


def run_pacre_vc_scalar_counterexample_receipt() -> dict[str, object]:
    """Reproduce the two frozen v22 cancellation false-rejections."""

    rows: list[dict[str, object]] = []
    for name, common_value, residual_value in (
        PACRE_VC_SCALAR_COUNTEREXAMPLES
    ):
        common = torch.tensor(common_value, dtype=torch.float32)
        residual = torch.tensor(residual_value, dtype=torch.float32)
        specific = (common + residual).contiguous()
        recovered = (specific - common).contiguous()
        error = float((recovered - residual).abs().item())
        tolerance = (
            PACRE_VC_LEGACY_ATOL
            + PACRE_VC_LEGACY_RTOL * abs(float(residual.item()))
        )
        legacy_allclose = bool(
            torch.isclose(
                recovered,
                residual,
                rtol=PACRE_VC_LEGACY_RTOL,
                atol=PACRE_VC_LEGACY_ATOL,
            )
        )
        replay = (common + residual).contiguous()
        exact_forward_replay = (
            tensor_content_fingerprint(replay.reshape(1))
            == tensor_content_fingerprint(specific.reshape(1))
        )

        phase = torch.stack(
            (common + residual, common - residual)
        ).reshape(1, 2, 1, 1, 1).contiguous()
        phase_mean = phase.mean(dim=1, keepdim=True).contiguous()
        phase_residual = (phase - phase_mean).contiguous()
        semantic = phase_roundoff_observations(
            phase,
            phase_mean,
            phase_residual,
        )
        rows.append(
            {
                "name": name,
                "common_hex": float(common.item()).hex(),
                "residual_hex": float(residual.item()).hex(),
                "specific_hex": float(specific.item()).hex(),
                "legacy_recovered_hex": float(recovered.item()).hex(),
                "legacy_absolute_error_hex": error.hex(),
                "legacy_tolerance_hex": tolerance.hex(),
                "legacy_v22_allclose": legacy_allclose,
                "legacy_failure_reproduced": (
                    not legacy_allclose and error > tolerance
                ),
                "same_operand_exact_forward_replay": exact_forward_replay,
                "phase_semantics": semantic.canonical_payload(),
                "inputs": {
                    "common": _tensor_summary(common.reshape(1)),
                    "residual": _tensor_summary(residual.reshape(1)),
                },
            }
        )
    gate_passed = (
        len(rows) == len(PACRE_VC_SCALAR_COUNTEREXAMPLES)
        and all(
            row["legacy_failure_reproduced"] is True
            and row["same_operand_exact_forward_replay"] is True
            and row["phase_semantics"]["passed"] is True
            for row in rows
        )
    )
    body: dict[str, object] = {
        "schema_version": PACRE_VC_SCALAR_COUNTEREXAMPLE_SCHEMA,
        "cases": rows,
        "expected_case_count": 2,
        "observed_case_count": len(rows),
        "legacy_formula_gate_eligible": False,
        "legacy_formula_decision_weight": 0,
        "new_verifier_gate_eligible": True,
        "gate_passed": gate_passed,
        "generated_only": True,
        "dataset_accessed": False,
        "cache_accessed": False,
        "D_R_accessed": False,
        "D_V_accessed": False,
        "D_T_accessed": False,
        "optimizer_constructed": False,
        "training_performed": False,
    }
    return {**body, "receipt_fingerprint": stable_fingerprint(body)}


__all__ = [
    "GeneratedPACREVCFormalInput",
    "PACRE_VC_FORMAL_BATCH_SIZE",
    "PACRE_VC_FORMAL_FEATURE_CHANNELS",
    "PACRE_VC_FORMAL_FEATURE_HEIGHT",
    "PACRE_VC_FORMAL_FEATURE_STRIDE",
    "PACRE_VC_FORMAL_FEATURE_WIDTH",
    "PACRE_VC_FORMAL_OCCUPANCY_HEIGHT",
    "PACRE_VC_FORMAL_OCCUPANCY_WIDTH",
    "PACRE_VC_FORMAL_STRESS_RUN_SCHEMA",
    "PACRE_VC_FORMAL_STRESS_SCHEMA",
    "PACRE_VC_FORMAL_STRESS_SEEDS",
    "PACRE_VC_FORMAL_WIDTH",
    "PACRE_VC_SCALAR_COUNTEREXAMPLE_SCHEMA",
    "generate_pacre_vc_formal_input",
    "run_pacre_vc_formal_numeric_stress_receipt",
    "run_pacre_vc_formal_numeric_stress_run",
    "run_pacre_vc_scalar_counterexample_receipt",
]
